// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyABYOLe5v_bMkFy41kBaihYIEL8OdV80I4',
    appId: '1:708697259052:web:e6b837d2d7d3fa4ff5a589',
    messagingSenderId: '708697259052',
    projectId: 'todo-6afe6',
    authDomain: 'todo-6afe6.firebaseapp.com',
    storageBucket: 'todo-6afe6.appspot.com',
    measurementId: 'G-E70G6Y4RME',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA1CXKbfIfZugKMD7jFFoo0-ofvblup72M',
    appId: '1:708697259052:android:2b4fe40a76b65453f5a589',
    messagingSenderId: '708697259052',
    projectId: 'todo-6afe6',
    storageBucket: 'todo-6afe6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDlQ6vrHmxsEfYzsUbjbEZBhes7KqnmOOo',
    appId: '1:708697259052:ios:8ab9fc3d2bc4dfc1f5a589',
    messagingSenderId: '708697259052',
    projectId: 'todo-6afe6',
    storageBucket: 'todo-6afe6.appspot.com',
    iosClientId: '708697259052-u1ej6tebi67f917qcc3ne8qldvsv0ui2.apps.googleusercontent.com',
    iosBundleId: 'com.example.todoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDlQ6vrHmxsEfYzsUbjbEZBhes7KqnmOOo',
    appId: '1:708697259052:ios:213a7982cb5be016f5a589',
    messagingSenderId: '708697259052',
    projectId: 'todo-6afe6',
    storageBucket: 'todo-6afe6.appspot.com',
    iosClientId: '708697259052-45slcv2b41rqv5e7prj2bmt0192b0ebr.apps.googleusercontent.com',
    iosBundleId: 'com.example.todoFirebase',
  );
}
